[package]
name = "fluid-simulation-bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
bevy = { version = "0.15.1" }
colorgrad = "0.7.0"

egui = "0.30.0"
bevy_egui = "0.32.0"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
codegen-units = 1
lto = false